GET http://localhost:3000/users/500


GET http://localhost:3000/users
?limit=20
&page=2


POST http://localhost:3000/users 
Content-Type: application/json

{
  "firstName":"John",
  "lastName":"Doe",
  "email":"john@doe2.com",
  "password":"Password@123"
}

PATCH http://localhost:3000/users 
Content-Type: application/json

{
  "email":"joh@doe.com"
}